#pragma once

#define FIRMWARE_VERSION "v3.1.5"
#define FIRMWARE_SEQ 300100500
#define UI_FILE "ui-0.9.6.bmp"
#define JSON_VERSION 2

#define NR_OF_PAGES 12
#define NR_OF_DEVICES 2
#define NR_OF_MIDI_INTERFACES 2
#define NR_OF_MIDI_CHANNELS 16
#define NR_OF_HW_BUTTONS 6
#define NR_OF_USB_DEVICES 2
#define NR_OF_HW_POTS 12
#define MAX_POT_ID 12
#define MIDI_CTRL_PORT 2

#define MAX_DEVICE_NAME_LENGTH 20
#define TOUCH_LONG_HOLD_TIME 250
#define MAX_FILENAME_LENGTH 64
#define MAX_DIRNAME_LENGTH 64
